name: Build

on:
  push: {branches: [main]}
  pull_request: {branches: [main]}

env: {CARGO_TERM_COLOR: always}

jobs:
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo build --release
    - uses: actions/upload-artifact@v2
      with: {name: fat-mac, path: target/release/fat}
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo build --release
    - uses: actions/upload-artifact@v2
      with: {name: fat.exe, path: target/release/fat.exe}
  build:
    needs: [mac, windows]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo clippy --release
    - run: cargo test --release
    - run: cargo build --release
    - uses: actions/upload-artifact@v2
      with: {name: fat, path: target/release/fat}
  tune:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: wget https://github.com/grasevski/hype/releases/download/latest/hype
    - run: chmod +x hype
    - run: ./hype -m "$(cat hype.json)" -- ./hype.sh -d 1s | tee tune.csv
    - uses: actions/upload-artifact@v2
      with: {name: tune.csv}
  delay:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: wget https://github.com/grasevski/hype/releases/download/latest/hype
    - run: chmod +x hype
    - run: ./hype -m "$(cat hype.json)" -- ./hype.sh -d 1d | tee delay.csv
    - uses: actions/upload-artifact@v2
      with: {name: delay.csv}
  release:
    needs: [tune, delay]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with: {name: fat}
    - uses: actions/download-artifact@v2
      with: {name: fat-mac}
    - run: mv fat fat-mac
    - uses: actions/download-artifact@v2
      with: {name: fat.exe}
    - uses: actions/download-artifact@v2
      with: {name: tune.csv}
    - uses: actions/download-artifact@v2
      with: {name: delay.csv}
    - uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/main'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        files: |
          LICENSE
          fat
          fat-mac
          fat.exe
          tune.csv
          delay.csv
